---
- hosts: all
  gather_facts: false
  roles:
    - app
- hosts: apps
  gather_facts: false
  roles:
     - tomcat
- hosts: frontends
  gather_facts: false
  roles:
      - haproxy
- hosts: appdbs
  gather_facts: false
  roles:
      - postgress

